#+title: 12th level ligma charsheet
#+description: 12th level fairy run
#+FILETAGS: dnd stats ligma

* Important stats
** HP
- Max :: 121
- Current :: 121
- Temp :: 121
** Armor Class
- 13
** Initiative
- +4
** Speed
- 30
** Money
| Copper | Silver | Electrum |  Gold | Platinum | Total (gp) |
|--------+--------+----------+-------+----------+------------|
|      0 |     10 |        0 | 11219 |     2500 |      36220 |
#+TBLFM: $6=(($1/100) + ($2 /10) + ($3 /2) + $4 + ($5 *10))
** Sorcerer Points
- 14
** Passive Perception
- 10
* Spell Slots
1. 1st Level
   1. [ ]
   2. [ ]
   3. [ ]
   4. [ ]
2. 2nd Level
   1. [ ]
   2. [ ]
   3. [ ]
3. 3rd Level
   1. [ ]
   2. [ ]
   3. [ ]
4. 4th Level
   1. [ ]
   2. [ ]
   3. [ ]
5. 5th level
   1. [ ]
   2. [ ]
6. 6th Level
   1. [ ]

* Spells
** Cantrips 8
**** Druidcraft :druid:phb:
- Casting Time :: 1 action
- Range :: 30 feet
- Components :: V, S
- Duration :: Instantaneous

Whispering to the spirits of nature, you create one of the following effects within range:

- You create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24
  hours. The effect might manifest as a golden orb for clear skies, a cloud for rain, falling snowflakes for snow, and
  so on. This effect persists for 1 round.

- You instantly make a flower blossom, a seed pod open, or a leaf bud bloom.

- You create an instantaneous, harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small
  animal, or the faint odor of skunk. The effect must fit in a 5-foot cube.

- You instantly light or snuff out a candle, a torch, or a small campfire.

**** Mind Sliver :sorcerer:warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V
- Duration :: 1 round

You drive a disorienting spike of psychic energy into the mind of one creature you can see within range. The target must succeed on an Intelligence saving throw or take 1d6 psychic damage and subtract 1d4 from the next saving throw it makes before the end of your next turn.

At Higher Levels. This spell’s damage increases by 1d6 when you reach certain levels: 5th level (2d6), 11th level (3d6), and 17th level (4d6).
**** Chill Touch :sorcerer:warlock:wizard:phb:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: 1 Round

You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the
creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can't regain
hit points until the start of your next turn. Until then, the hand clings to the target.

If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.

This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).
**** Mage Hand :artificer:bard:sorcerer:warlock:wizard:
+ Casting Time :: 1 action
+ Range :: 30 feet
+ Components :: V, S
+ Duration :: 1 minute

 A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.

 You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it.

 The hand can’t attack, activate magical items, or carry more than 10 pounds.

**** Shocking Grasp :sorcerer:wizard:
- Casting Time :: 1 action
- Range :: Touch
- Components :: V, S
- Duration :: Instantaneous

Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against
the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target
takes 1d8 lightning damage, and it can't take reactions until the start of its next turn.

The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).

**** Sword Burst :arificer:sorcerer:warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: Self
- Components :: V
- Duration :: Instantaneous
 Fill in later
**** Light :bard:cleric:sorcerer:wizard:phb:
- Casting Time :: 1 action
- Range :: Touch
- Components :: V, M (a firefly or phosphorescent moss)
- Duration :: 1 hour
  You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action.

  If you target an object held or worn by a hostile creature, that creature must succeed on a Dexterity saving throw to avoid the spell.

**** Fire Bolt :artificer:sorcerer:wizard:phb:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: Instantaneous
  You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.

  This spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).

** Spells Known
1. 1st
   1. Arms of Hadar (Slotless)
   2. Dissonant Whispers (Slotless)
   3. Faerie Fire (Slotless 1/day /Slot optional)
   4. Chaos Bolt
   5. Mage Armor
   6. Magic Missle
   7. Mind Sliver
2. 2nd
   1. Calm Emotions (Slotless)
   2. Detect Thoughts (Slotless)
   3. Enlarge/Reduce (Slotless 1/day /Slot optional)
   4. Blur
   5. Flaming Sphere
   6. Warding Wind
3. 3rd
   1. Hunger of Hadar (Slotless)
   2. Sending (Slotless)
   3. Fireball
4. 4th
   1. Evards Black Tentacles (Slotless)
   2. Summon Abberation (Slotless)
   3. Vitriolic Sphere
5. 5th
   1. Rary's Telepathic Bond (Slotless)
   2. Telekinesis (Slotless)
   3. Cloudkill
   4. Hold Monster
   5. Synaptic Static
6. 6th
   1. Disintegrate

** Spells Described
*** 1st Level
**** Faerie Fire :bard:druid:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V
- Duration :: Concentration, up to 1 minute

Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in
the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration,
objects and affected creatures shed dim light in a 10-foot radius.

Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected
creature or object can't benefit from being invisible.

**** Mage Armor :sorcerer:wizard:phb:
- Casting Time :: 1 action
- Range :: Touch
- Components :: V, S, M (a piece of cured leather)
- Duration :: 8 hours

You touch a willing creature who isn't wearing armor, and a protective magical force surrounds it until the spell ends.
The target's base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the
spell as an action.

**** Magic Missile :sorcerer:wizard:phb:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: Instantaneous

You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range.
A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one
creature or several.

- At Higher Levels ::
  When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot
  level above 1st.

**** Arms of Hadar :warlock:phb:
- Casting Time :: 1 action
- Range :: Self (10-foot radius)
- Components :: V, S
- Duration :: Instantaneous
  You invoke the power of Hadar, the Dark Hunger. Tendrils of dark energy erupt from you and batter all creatures within 10 feet of you. Each creature in that area must make a Strength saving throw. On a failed save, a target takes 2d6 necrotic damage and can’t take reactions until its next turn. On a successful save, the creature takes half damage, but suffers no other effect.

- At Higher Levels ::
  When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.

**** Dissonant Whispers :bard:phb:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V
- Duration :: Instantaneous

  You whisper a discordant melody that only one creature of your choice within range can hear, wracking it with terrible pain. The target must make a Wisdom saving throw. On a failed save, it takes 3d6 psychic damage and must immediately use its reaction, if available, to move as far as its speed allows away from you. The creature doesn’t move into obviously dangerous ground, such as a fire or a pit. On a successful save, the target takes half as much damage and doesn’t have to move away. A deafened creature automatically succeeds on the save.

- At Higher Levels ::
  When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.

**** Chaos Bolt :sorcerer:xge:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: Instantaneous

  You hurl an undulating, warbling mass of chaotic energy at one creature in range. Make a ranged spell attack against the target. On a hit, the target takes 2d8 + 1d6 damage. Choose one of the d8s. The number rolled on that die determines the attack's damage type, as shown below.

| d8 | Damage Type |
|----+-------------|
|  1 | Acid        |
|  2 | Cold        |
|  3 | Fire        |
|  4 | Force       |
|  5 | Lightning   |
|  6 | Poison      |
|  7 | Psychic     |
|  8 | Thunder     |

  If you roll the same number on both d8s, the chaotic energy leaps from the target to a different creature of your choice within 30 feet of it. Make a new attack roll against the new target, and make a new damage roll, which could cause the chaotic energy to leap again.

  A creature can be targeted only once by each casting of this spell.

- At Higher Levels ::
  When you cast this spell using a spell slot of 2nd level or higher, each target takes 1d6 extra damage of the type rolled for each slot level above 1st.
**** Mind Sliver :sorcerer:warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V
- Duration :: 1 round

  You drive a disorienting spike of psychic energy into the mind of one creature you can see within range. The target must succeed on an Intelligence saving throw or take 1d6 psychic damage and subtract 1d4 from the next saving throw it makes before the end of your next turn.

- At Higher Levels ::
  This spell’s damage increases by 1d6 when you reach certain levels: 5th level (2d6), 11th level (3d6), and 17th level (4d6).
*** 2nd Level
**** Flaming Sphere :druid:wizard:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V, S, M (a bit of tallow, a pinch of brimstone, and adjusting of powdered iron)
- Duration :: Concentration, up to 1 minute

A 5-foot diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration.
Any creature that ends its turn within 5 feet of the sphere must make a Dexterity saving throw. The creature takes 2d6
fire damage on a failed save, or half as much damage on a successful one.

As a bonus action, you can move the sphere up to 30 feet. If you ram the sphere into a creature, that creature must make
the saving throw against the sphere's damage, and the sphere stops moving this turn.

When you move the sphere, you can direct it over barriers up to 5 feet tall and jump it across pits up to 10 feet wide.
The sphere ignites flammable objects not being worn or carried, and it sheds bright light in a 20-foot radius and dim
light for an additional 20 feet.

- At Higher Levels ::
  When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot level
  above 2nd.

**** Calm Emotions :bard:cleric:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V, S
- Duration :: Concentration, up to 1 minute

You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot radius sphere centered on a
point you choose within range must make a Charisma saving throw; a creature can choose to fail this saving throw if it
wishes. If a creature fails its saving throw, choose one of the following two effects.

You can suppress any effect causing a target to be charmed or frightened. When this spell ends, any suppressed effect
resumes, provided that its duration has not expired in the meantime.

Alternatively, you can make a target indifferent about creatures of your choice that it is hostile toward. This
indifference ends if the target is attacked or harmed by a spell or if it witnesses any of its friends being harmed.
When the spell ends, the creature becomes hostile again, unless the GM rules otherwise.

**** Blur :sorcerer:wizard:
- Casting Time :: 1 action
- Range :: Self
- Components :: V
- Duration :: Concentration, up to 1 minute

Your body becomes blurred, shifting and wavering to all who can see you.
For the duration, any creature has disadvantage on attack rolls against
you. An attacker is immune to this effect if it doesn't rely on sight,
as with blindsight, or can see through illusions, as with truesight.

**** Enlarge/Reduce :sorcerer:wizard:
- Casting Time :: 1 action
- Range :: 30 feet
- Components :: V, S, M (a pinch of powdered iron)
- Duration :: Concentration, up to 1 minute

  You cause a creature or an object you can see within range to grow
  larger or smaller for the duration. Choose either a creature or an
  object that is neither worn nor carried. If the target is unwilling, it
  can make a Constitution saving throw. On a success, the spell has no
  effect.

  If the target is a creature, everything it is wearing and carrying
  changes size with it. Any item dropped by an affected creature returns
  to normal size at once.

- Enlarge ::
  The target's size doubles in all dimensions, and its weight
  is multiplied by eight. This growth increases its size by one category-
  from Medium to Large, for example. If there isn't enough room for the
  target to double its size, the creature or object attains the maximum
  possible size in the space available. Until the spell ends, the target
  also has advantage on Strength checks and Strength saving throws. The
  target's weapons also grow to match its new size. While these weapons
  are enlarged, the target's attacks with them deal 1d4 extra damage.

- Reduce ::
  The target's size is halved in all dimensions, and its
  weight is reduced to one-eighth of normal. This reduction decreases its
  size by one category-from Medium to Small, for example. Until the spell
  ends, the target also has disadvantage on Strength checks and Strength
  saving throws. The target's weapons also shrink to match its new size.
  While these weapons are reduced, the target's attacks with them deal 1d4
  less damage (this can't reduce the damage below 1).

**** Warding Wind :bard:druid:sorcerer:wizard:xge:
- Casting Time :: 1 action
- Range :: Self
- Components :: V
- Duration :: Concentration, up to 10 minutes
  A strong wind (20 miles per hour) blows around you in a 10-foot radius and moves with you, remaining centered on you. The wind lasts for the spell’s duration.

  The wind has the following effects:
  - It deafens you and other creatures in its area.
  - It extinguishes unprotected flames in its area that are torch-sized or smaller.
  - The area is difficult terrain for creatures other than you.
  - The attack rolls of ranged weapon attacks have disadvantage if they pass in or out of the wind.
  - It hedges out vapor, gas, and fog that can be dispersed by strong wind.

**** Detect Thoughts :bard:sorcerer:wizard:phb:
- Casting Time :: 1 action
- Range :: Self
- Components :: V, S, M (a copper piece)
- Duration :: Concentration, up to 1 minute

  For the duration, you can read the thoughts of certain creatures. When you cast the spell and as your action on each turn until the spell ends, you can focus your mind on any one creature that you can see within 30 feet of you. If the creature you choose has an Intelligence of 3 or lower or doesn’t speak any language, the creature is unaffected.

  You initially learn the surface thoughts of the creature—what is most on its mind in that moment. As an action, you can either shift your attention to another creature’s thoughts or attempt to probe deeper into the same creature’s mind. If you probe deeper, the target must make a Wisdom saving throw. If it fails, you gain insight into its reasoning (if any), its emotional state, and something that loom s large in its mind (such as something it worries over, loves, or hates). If it succeeds, the spell ends. Either way, the target knows that you are probing into its mind, and unless you shift your attention to another creature’s thoughts, the creature can use its action on its turn to make an Intelligence check contested by your Intelligence check; if it succeeds, the spell ends.

  Questions verbally directed at the target creature naturally shape the course of its thoughts, so this spell is particularly effective as part of an interrogation.

  You can also use this spell to detect the presence of thinking creatures you can’t see. When you cast the spell or as your action during the duration, you can search for thoughts within 30 feet of you. The spell can penetrate barriers, but 2 feet of rock, 2 inches of any metal other than lead, or a thin sheet of lead blocks you. You can’t detect a creature with an Intelligence of 3 or lower or one that doesn’t speak any language.

  Once you detect the presence of a creature in this way, you can read its thoughts for the rest of the duration as described above, even if you can’t see it, but it must still be within range.
*** 3rd Level
**** Fireball :sorcerer:wizard:
- Casting Time :: 1 action
- Range :: 150 feet
- Components :: V, S, M (a tiny ball of bat guano and sulfur)
- Duration :: Instantaneous

A bright streak flashes from your pointing finger to a point you choose
within range and then blossoms with a low roar into an explosion of
flame. Each creature in a 20-foot radius sphere centered on that point
must make a Dexterity saving throw. A target takes 8d6 fire damage on a
failed save, or half as much damage on a successful one.

The fire spreads around corners. It ignites flammable objects in the
area that aren't being worn or carried.

- At Higher Levels ::
  When you cast this spell using a spell slot of 4th
  level or higher, the damage increases by 1d6 for each slot level above
  3rd.

**** Hunger of Hadar :warlock:phb:
- Casting Time :: 1 action
- Range :: 150 feet
- Components :: V, S, M (a pickled octopus tentacle)
- Duration :: Concentration, up to 1 minute

  You open a gateway to the dark between the stars, a region infested with unknown horrors. A 20-foot-radius sphere of blackness and bitter cold appears, centered on a point with range and lasting for the duration. This void is filled with a cacophony of soft whispers and slurping noises that can be heard up to 30 feet away. No light, magical or otherwise, can illuminate the area, and creatures fully within the area are blinded.

  The void creates a warp in the fabric of space, and the area is difficult terrain. Any creature that starts its turn in the area takes 2d6 cold damage. Any creature that ends its turn in the area must succeed on a Dexterity saving throw or take 2d6 acid damage as milky, otherwordly tentacles rub against it.
**** Sending :bard:cleric:wizard:phb:
- Casting Time :: 1 action
- Range :: Unlimited
- Components :: V, S, M (a short piece of fine copper wire)
- Duration :: 1 round

  You send a short message of twenty-five words or less to a creature with which you are familiar. The creature hears the message in its mind, recognizes you as the sender if it knows you, and can answer in a like manner immediately. The spell enables creatures with Intelligence scores of at least 1 to understand the meaning of your message.

  You can send the message across any distance and even to other planes of existence, but if the target is on a different plane than you, there is a 5 percent chance that the message doesn’t arrive.
*** 4th level
**** Evard's Black Tentacles :wizard:phb:
- Casting Time :: 1 action
- Range :: 90 feet
- Components :: V, S, M (a piece of tentacle from a giant octopus or a giant squid)
- Duration :: Concentration, up to 1 minute

  Squirming, ebony tentacles fill a 20-foot square on ground that you can see within range. For the duration, these tentacles turn the ground in the area into difficult terrain.

  When a creature enters the affected area for the first time on a turn or starts its turn there, the creature must succeed on a Dexterity saving throw or take 3d6 bludgeoning damage and be restrained by the tentacles until the spell ends. A creature that starts its turn in the area and is already restrained by the tentacles takes 3d6 bludgeoning damage.

  A creature restrained by the tentacles can use its action to make a Strength or Dexterity check (its choice) against your spell save DC. On a success, it frees itself.
**** Summon Abberation :warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: 90 feet
- Components :: V, S, M (a pickled tentacle and an eyeball in a platinum inlaid vial worth at least 400 gp)
- Duration :: Concentration, up to 1 hour

  You call forth an aberrant spirit. It manifests in an unoccupied space that you can see within range. This corporeal form uses the Aberrant Spirit stat block. When you cast the spell, choose Beholderkin, Slaad, or Star Spawn. The creature resembles an aberration of that kind, which determines certain traits in its stat block. The creature disappears when it drops to 0 hit points or when the spell ends.

  The creature is an ally to you and your companions. In combat, the creature shares your initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it take the Dodge action and uses its move to avoid danger.

  - At Higher Levels ::
    When you cast this spell using a spell slot of 5th level or higher, use the higher level wherever the spell's level appears on the stat block.

    + Aberrant Spirit ::
      +  Medium aberration
        + Armor Class ::
           11 + the level of the spell (natural armor)
        + Hit Points ::
           40 + 10 for each spell level above 4th
        + Speed :: 30 ft., fly 30 ft. (hover) (Beholderkin only)
| STR     | DEX     | CON     | INT     | WIS     | CHA    |
|---------+---------+---------+---------+---------+--------|
| 16 (+3) | 10 (+0) | 15 (+2) | 16 (+3) | 10 (+0) | 6 (−2) |
- Damage Immunities :: Psychic
- Senses :: darkvision 60 ft., passive Perception 10
- Languages :: Deep Speech, understands the languages you speak
- Challenge :: —
- Proficiency Bonus :: equals your bonus
- Regeneration (Slaad Only) ::
  The aberration regains 5 hit points at the start of its turn if it has at least 1 hit point.
- Whispering Aura (Star Spawn Only) ::
  At the start of each of the aberration’s turns, each creature within 5 feet of the aberration must succeed on a Wisdom saving throw against your spell save DC or take 2d6 psychic damage, provided that the aberration isn’t incapacitated.
- Actions ::
  + Multiattack ::
    The aberration makes a number of attacks equal to half this spell’s level (rounded down).
  + Claws (Slaad Only) ::
    - Melee Weapon Attack :: your spell attack modifier to hit, reach 5 ft., one target.
    - Hit :: 1d10 + 3 + the spell’s level slashing damage. If the target is a creature, it can’t regain hit points until the start of the aberration’s next turn.
  + Eye Ray (Beholderkin Only) ::
    - Ranged Spell Attack :: your spell attack modifier to hit, range 150 ft., one creature.
    - Hit :: 1d8 + 3 + the spell’s level psychic damage.
  + Psychic Slam (Star Spawn Only) ::
    Melee Spell Attack: your spell attack modifier to hit, reach 5 ft., one creature. Hit: 1d8 + 3 + the spell’s level psychic damage
**** Vitriolic Sphere :sorcerer:wizard:xge:
- Casting Time :: 1 action
- Range :: 150 feet
- Components :: V, S, M (a drop of giant slug bile)
- Duration :: Instantaneous

You point at a place within range, and a glowing 1-foot ball of emerald acid streaks there and explodes in a 20-foot radius. Each creature in that area must make a Dexterity saving throw. On a failed save, a creature takes 10d4 acid damage and 5d4 acid damage at the end of its next turn. On a successful save, a creature takes half the initial damage and no damage at the end of its next turn.

- At Higher Levels ::
  When you cast this spell using a spell slot of 5th level or higher, the initial damage increases by 2d4 for each slot level above 4th.
*** 5th level
**** Cloudkill :sorcerer:wizard:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: Concentration, up to 10 minutes

You create a 20-foot radius sphere of poisonous, yellow-green fog
centered on a point you choose within range. The fog spreads around
corners. It lasts for the duration or until strong wind disperses the
fog, ending the spell. Its area is heavily obscured.

When a creature enters the spell's area for the first time on a turn or
starts its turn there, that creature must make a Constitution saving
throw. The creature takes 5d8 poison damage on a failed save, or half as
much damage on a successful one. Creatures are affected even if they
hold their breath or don't need to breathe.

The fog moves 10 feet away from you at the start of each of your turns,
rolling along the surface of the ground. The vapors, being heavier than
air, sink to the lowest level of the land, even pouring down openings.

- At Higher Levels ::
  When you cast this spell using a spell slot of 6th
  level or higher, the damage increases by 1d8 for each slot level above
  5th.

**** Hold Monster :bard:sorcerer:warlock:wizard:
- Casting Time :: 1 action
- Range :: 90 feet
- Components :: V, S, M (a small, straight piece of iron)
- Duration :: Concentration, up to 1 minute

Choose a creature that you can see within range. The target must succeed
on a Wisdom saving throw or be paralyzed for the duration. This spell
has no effect on undead. At the end of each of its turns, the target can
make another Wisdom saving throw. On a success, the spell ends on the
target.

- At Higher Levels ::
  When you cast this spell using a spell slot of 6th
  level or higher, you can target one additional creature for each slot
  level above 5th. The creatures must be within 30 feet of each other when
  you target them.

**** Telekinesis :sorcerer:wizard:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V, S
- Duration :: Concentration, up to 10 minutes
  You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as your action each round for the duration, you can exert your will on one creature or object that you can see within range, causing the appropriate effect below. You can affect the same target round after round, or choose a new one at any time. If you switch targets, the prior target is no longer affected by the spell.

- Creature ::
  You can try to move a Huge or smaller creature. Make an
  ability check with your spellcasting ability contested by the creature's
  Strength check. If you win the contest, you move the creature up to 30
  feet in any direction, including upward but not beyond the range of this
  spell. Until the end of your next turn, the creature is restrained in
  your telekinetic grip. A creature lifted upward is suspended in mid-air.

  On subsequent rounds, you can use your action to attempt to maintain
  your telekinetic grip on the creature by repeating the contest.

- Object ::
  You can try to move an object that weighs up to 1,000
  pounds. If the object isn't being worn or carried, you automatically
  move it up to 30 feet in any direction, but not beyond the range of this
  spell.

  If the object is worn or carried by a creature, you must make an ability
  check with your spellcasting ability contested by that creature's
  Strength check. If you succeed, you pull the object away from that
  creature and can move it up to 30 feet in any direction but not beyond
  the range of this spell.

  You can exert fine control on objects with your telekinetic grip, such
  as manipulating a simple tool, opening a door or a container, stowing or
  retrieving an item from an open container, or pouring the contents from
  a vial.

**** Synaptic Static :bard:sorcerer:warlock:wizard:xge:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: Instantaneous

  You choose a point within range and cause psychic energy to explode there. Each creature in a 20-foot-radius sphere centered on that point must make an Intelligence saving throw. A creature with an Intelligence score of 2 or lower can’t be affected by this spell. A target takes 8d6 psychic damage on a failed save, or half as much damage on a successful one.

  After a failed save, a target has muddled thoughts for 1 minute. During that time, it rolls a d6 and subtracts the number rolled from all its attack rolls and ability checks, as well as its Constitution saving throws to maintain concentration. The target can make an Intelligence saving throw at the end of each of its turns, ending the effect on itself on a success.

**** Rary's Telepathic Bond :bard:wizard:phb:
- Casting Time :: 1 action
- Range :: 30 feet
- Components :: V, S, M (pieces of eggshell from two different kinds of creatures)
- Duration :: 1 hour

  You forge a telepathic link among up to eight willing creatures of your choice within range, psychically linking each creature to all the others for the duration. Creatures with Intelligence scores of 2 or less aren’t affected by this spell.

  Until the spell ends, the targets can communicated telepathically through the bond whether or not they have a common language. The communication is possible over any distance, though it can’t extend to other planes of existence.

*** 6th level
**** Disintegrate :sorcerer:wizard:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V, S, M (a lodestone and a pinch of dust)
- Duration :: Instantaneous

  A thin green ray springs from your pointing finger to a target that you can see within range. The target can be a creature, an object, or a creation of magical force, such as the wall created by [[*Wall of Force][Wall of Force]].

  A creature targeted by this spell must make a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 force damage. The target is disintegrated if this damage leaves it with 0 hit points.

  A disintegrated creature and everything it is wearing and carrying, except magic items, are reduced to a pile of fine gray dust. The creature can be restored to life only by means of a [[*True Resurrection][True Resurrection]] or a [[*Wish][Wish]] spell.

  This spell automatically disintegrates a Large or smaller nonmagical object or a creation of magical force. If the target is a Huge or larger object or creation of force, this spell disintegrates a 10-foot cube portion of it. A magic item is unaffected by this spell.

- At Higher Levels ::
  When you cast this spell using a spell slot of 7th
  level or higher, the damage increases by 3d6 for each slot level above
  6th.

* Abilities and Skills
  #+name: stats
  | Ability | Score | Mod | PB | Roll      | Skill           |
  |---------+-------+-----+----+-----------+-----------------|
  | STR     |     9 |  -1 |    | 1d20 + -1 | Saving Throw    |
  |         |       |     |    | 1d20 + -1 | Athletics       |
  |---------+-------+-----+----+-----------+-----------------|
  | DEX     |    16 |   3 |    | 1d20 + 3  | Saving Throw    |
  |         |       |     |    | 1d20 + 3  | Acrobatics      |
  |         |       |     |    | 1d20 + 3  | Sleight of Hand |
  |         |       |     |  7 | 1d20 + 3  | Stealth         |
  |---------+-------+-----+----+-----------+-----------------|
  | CON     |    19 |   4 |  8 | 1d20 + 4  | Saving Throw    |
  |---------+-------+-----+----+-----------+-----------------|
  | INT     |    11 |   0 |    | 1d20 + 0  | Saving Throw    |
  |         |       |     |    | 1d20 + 0  | Arcana          |
  |         |       |     |    | 1d20 + 0  | History         |
  |         |       |     |    | 1d20 + 0  | Investigation   |
  |         |       |     |    | 1d20 + 0  | Nature          |
  |         |       |     |    | 1d20 + 0  | Religion        |
  |---------+-------+-----+----+-----------+-----------------|
  | WIS     |    11 |   0 |    | 1d20 + 0  | Saving Throw    |
  |         |       |     |    | 1d20 + 0  | Animal Handling |
  |         |       |     |    | 1d20 + 0  | Insight         |
  |         |       |     |    | 1d20 + 0  | Medicine        |
  |         |       |     |    | 1d20 + 0  | Perception      |
  |         |       |     |    | 1d20 + 0  | Survival        |
  |---------+-------+-----+----+-----------+-----------------|
  | CHA     |    20 |   5 |  8 | 1d20 + 5  | Saving Throw    |
  |         |       |     |  8 | 1d20 + 5  | Deception       |
  |         |       |     |  8 | 1d20 + 5  | Intimidation    |
  |         |       |     |  0 | 1d20 + 5  | Performance     |
  |         |       |     |  8 | 1d20 + 5  | Persuasion      |
  |---------+-------+-----+----+-----------+-----------------|
  | PROF    |     4 |     |    |           |                 |
  #+TBLFM: @2$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @4$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @8$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @9$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @15$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @21$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @2$5..@3$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @2$1))))))
  #+TBLFM: @4$5..@7$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @4$1))))))
  #+TBLFM: @8$5..@8$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @8$1))))))
  #+TBLFM: @9$5..@14$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @9$1))))))
  #+TBLFM: @15$5..@20$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @15$1))))))
  #+TBLFM: @21$5..@25$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @21$1))))))

* Equipment
| Name                | Quantity | Cost (gp) | Weight (lbs) | Total Weight (lbs) | Total Cost (gp) |
|---------------------+----------+-----------+--------------+--------------------+-----------------|
| Light Crossbow      |        1 |        25 |            5 |                  5 |              25 |
| Crossbow bolts (20) |        2 |         1 |          1.5 |                  3 |              40 |
| Dagger              |        4 |         2 |            1 |                  4 |               8 |
| Arcane Focus, Orb   |        1 |        20 |            3 |                  3 |              20 |
| Backpack            |        1 |         2 |            5 |                  5 |               2 |
| Ball Bearings (1k)  |        2 |         1 |            2 |                  4 |               2 |
| Healer's Kit        |        1 |         5 |            3 |                  3 |               5 |
| Crowbar             |        1 |         2 |            5 |                  5 |               2 |
| Hammer              |        1 |         1 |            3 |                  3 |               1 |
| Piton               |       10 |       .05 |          .25 |                2.5 |             0.5 |
| Torch               |       10 |       .01 |            1 |                 10 |             0.1 |
| Tinderbox           |        1 |        .5 |            1 |                  1 |             0.5 |
| Ration              |       10 |        .5 |            2 |                 20 |              5. |
| Bedroll             |        1 |         1 |            2 |                  2 |               1 |
| Waterskin           |        1 |        .2 |            5 |                  5 |             0.2 |
| Hempen Rope (50ft)  |        1 |         1 |           10 |                 10 |               1 |
| Robes               |        1 |         1 |            4 |                  4 |               1 |
| Climbers Kit        |        1 |        25 |           12 |                 12 |              25 |
|---------------------+----------+-----------+--------------+--------------------+-----------------|
| Carry Capacity      |       90 |           |              |              148.5 |           124.3 |
#+TBLFM: $5=($2 * $4)
#+TBLFM: $6=($2 * $3)
#+TBLFM: @>$5=vsum(@<<$5..@>>$5)
#+TBLFM: @>$6=vsum(@<<$6..@>>$6)
#+TBLFM: @>$2=($STR * 10)

* Traits
  | Level | Race  | Subrace | Class    | Subclass      | Age | Alignment    | Size        |
  |-------+-------+---------+----------+---------------+-----+--------------+-------------|
  |    12 | Fairy | N/A     | Sorcerer | Abberant Mind |  30 | Chaotic Good | Small (3ft) |

* Constants
  #+NAME: define-constants-with-src-block
  #+BEGIN_SRC elisp :var table=stats :colnames yes :results output drawer :cache yes :lang elisp
    (dnd-output-ability-constants table)
    #+END_SRC

    #+RESULTS[87ad1d0bfe6e86e226ace44824ec4d05b899ea9a]: define-constants-with-src-block
    :results:
    #+CONSTANTS: STR=9
    #+CONSTANTS: DEX=16
    #+CONSTANTS: CON=19
    #+CONSTANTS: INT=11
    #+CONSTANTS: WIS=11
    #+CONSTANTS: CHA=20
    #+CONSTANTS: PROF=4
    :end:

* Abilities and Skills
  #+name: stats
  | Ability | Score | Mod | PB | Roll      | Skill           |
  |---------+-------+-----+----+-----------+-----------------|
  | STR     |     9 |  -1 |    | 1d20 + -1 | Saving Throw    |
  |         |       |     |    | 1d20 + -1 | Athletics       |
  |---------+-------+-----+----+-----------+-----------------|
  | DEX     |    16 |   3 |    | 1d20 + 3  | Saving Throw    |
  |         |       |     |    | 1d20 + 3  | Acrobatics      |
  |         |       |     |    | 1d20 + 3  | Sleight of Hand |
  |         |       |     |  7 | 1d20 + 3  | Stealth         |
  |---------+-------+-----+----+-----------+-----------------|
  | CON     |    19 |   4 |  8 | 1d20 + 4  | Saving Throw    |
  |---------+-------+-----+----+-----------+-----------------|
  | INT     |    11 |   0 |    | 1d20 + 0  | Saving Throw    |
  |         |       |     |    | 1d20 + 0  | Arcana          |
  |         |       |     |    | 1d20 + 0  | History         |
  |         |       |     |    | 1d20 + 0  | Investigation   |
  |         |       |     |    | 1d20 + 0  | Nature          |
  |         |       |     |    | 1d20 + 0  | Religion        |
  |---------+-------+-----+----+-----------+-----------------|
  | WIS     |    11 |   0 |    | 1d20 + 0  | Saving Throw    |
  |         |       |     |    | 1d20 + 0  | Animal Handling |
  |         |       |     |    | 1d20 + 0  | Insight         |
  |         |       |     |    | 1d20 + 0  | Medicine        |
  |         |       |     |    | 1d20 + 0  | Perception      |
  |         |       |     |    | 1d20 + 0  | Survival        |
  |---------+-------+-----+----+-----------+-----------------|
  | CHA     |    20 |   5 |  8 | 1d20 + 5  | Saving Throw    |
  |         |       |     |  8 | 1d20 + 5  | Deception       |
  |         |       |     |  8 | 1d20 + 5  | Intimidation    |
  |         |       |     |  0 | 1d20 + 5  | Performance     |
  |         |       |     |  8 | 1d20 + 5  | Persuasion      |
  |---------+-------+-----+----+-----------+-----------------|
  | PROF    |     4 |     |    |           |                 |
  #+TBLFM: @2$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @4$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @8$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @9$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @15$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @21$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @2$5..@3$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @2$1))))))
  #+TBLFM: @4$5..@7$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @4$1))))))
  #+TBLFM: @8$5..@8$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @8$1))))))
  #+TBLFM: @9$5..@14$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @9$1))))))
  #+TBLFM: @15$5..@20$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @15$1))))))
  #+TBLFM: @21$5..@25$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @21$1))))))

* Proficiencies
  | Languages | Tools          | Armor | Weapons |
  |-----------+----------------+-------+---------|
  | Common    | Thieves' Tools |       | Simple  |
  | Sylvan    | Flute          |       |         |
  |           | Dice           |       |         |

* Stats
| Walking Speed | Flying speed | Climbing Speed | Hit Points | AC            | Death Saves | Inspiration |
|---------------+--------------+----------------+------------+---------------+-------------+-------------|
|            30 |           30 |             15 | 121/121    | 13 (16 w M.A) |             |             |

| Skill           | Ability | Prof | Mod | Roll      |
|-----------------+---------+------+-----+-----------|
| Acrobatics      | DEX     |      |   0 | 1d20 + 0  |
| Animal Handling | WIS     |      |   0 | 1d20 + 0  |
| Arcana          | INT     |      |   0 | 1d20 + 0  |
| Athletics       | STR     |      |  -1 | 1d20 + -1 |
| Deception       | CHA     |      |   0 | 1d20 + 0  |
| History         | INT     |      |   0 | 1d20 + 0  |
| Insight         | WIS     |      |   0 | 1d20 + 0  |
| Intimidation    | CHA     |      |   0 | 1d20 + 0  |
| Investigation   | INT     |      |   0 | 1d20 + 0  |
| Medicine        | WIS     |      |   0 | 1d20 + 0  |
| Nature          | INT     |      |   0 | 1d20 + 0  |
| Perception      | WIS     |      |   0 | 1d20 + 0  |
| Performance     | CHA     |      |   0 | 1d20 + 0  |
| Persuasion      | CHA     |      |   0 | 1d20 + 0  |
| Religion        | INT     |      |   0 | 1d20 + 0  |
| Sleight of Hand | DEX     |      |   0 | 1d20 + 0  |
| Stealth         | DEX     |      |   0 | 1d20 + 0  |
| Survival        | WIS     |      |   0 | 1d20 + 0  |
#+TBLFM: $5='(concat "1d20 + " $4)

* Attacks
  #+NAME: attacks
  | Weapon          | Ability | PB | Type                          | Die | Mod To Hit | Roll    |
  |-----------------+---------+----+-------------------------------+-----+------------+---------|
  | Crossbow, Light | DEX     |    | Piercing                      | 1d8 |          3 | 1d8 + 3 |
  | Dagger          | DEX     |    | Finesse, Light, Thrown(20/60) | 1d4 |          3 | 1d4 + 3 |
  | Shortsword      | DEX     |    | Piercing                      | 1d6 |          3 | 1d6 + 3 |
  #+TBLFM: $6='(+ (calc-dnd-pb $PROF $3) (calc-dnd-mod (string-to-number (org-table-get-constant $2))))
  #+TBLFM: $7='(concat $5 " + " (number-to-string (calc-dnd-mod (string-to-number (org-table-get-constant $2)))))

* Equipment
** Weapons
- crossbow, light, 20 bolts
- simple weapon
- two daggers
- Weapon of Warning ::
  This magic weapon warns you of danger. While the weapon is on your person, you have advantage on initiative rolls. In addition, you and any of your companions within 30 feet of you can't be surprised, except when incapacitated by something other than nonmagical sleep. The weapon magically awakens you and your companions within range if any of you are sleeping naturally when combat begins.

** Items
- component pouch
- bedroll
  - 2lb
- blanket
  - 5lb
- healer's kit
  - 3lb
- 4 ball bearing bags
  - 2lbx4
** Wonderous Items
*** Uncommon 3
**** Immovable Rod :dmg:
- This flat iron rod has a button on one end. You can use an action to press the button, which causes the rod to become magically fixed in place. Until you or another creature uses an action to push the button again, the rod doesn't move, even if it is defying gravity. The rod can hold up to 8,000 pounds of weight. More weight causes the rod to deactivate and fall. A creature can use an action to make a DC 30 Strength check, moving the fixed rod up to 10 feet on a success.
**** Luckstone :attuned:dmg:
- +1 to ability checks and saving throws
**** Weapon of Warning :attuned:dmg:
- This magic weapon warns you of danger. While the weapon is on your person, you have advantage on initiative rolls. In addition, you and any of your companions within 30 feet of you can't be surprised, except when incapacitated by something other than nonmagical sleep. The weapon magically awakens you and your companions within range if any of you are sleeping naturally when combat begins.
*** Rare 1
**** Amulet of Health :attuned:dmg:
- Your Constitution score is 19 while you wear this amulet. It has no effect on you if your Constitution is 19 or higher without it.
*** Very Rare 0
+
*** Attunements 3
**** Amulet of Health
**** Luckstone
**** Weapon of Warning
** Dungeoneer's Pack
- backpack
- crowbar
- hammer
- 10 pitons
- 10 torches
- tinderbox
- 10 rations
- waterskin
- hempen rope, 50 ft

* Info
** Name
*** Lazuli Islecloud Greenspirit Morel Aspencone
*** L.I.G.M.A
** Group Name
*** The Winged Ones
** Weight
*** 30
** Eyes
*** Green
** Skin
*** yes
** Hair
*** Yes
** XP
*** somenum
** HP
*** 1d6 (or 5) + con mod / sorc level after 1st
*** 96? + 24
* Personality
** Urban Bounty Hunter
*** Ear to the Ground
**** You are in frequent contact with people in the segment of society that your chosen quarries move through. These people might be associated with the criminal underworld, the rough-and-tumble folk of the streets, or members of high society. This connection comes in the form of a contact in any city you visit, a person who provides information about the people and places of the local area.
** Traits
*** I would rather make a new friend than a new enemy.
** Ideals
*** Redemption. There's a spark of good in everyone. (Good)
** Bonds
*** I'm guilty of a terrible crime. I hope I can redeem myself for it.
** Flaws
*** If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.
* Constants
  #+NAME: define-constants-with-src-block
  #+BEGIN_SRC elisp :var table=stats :colnames yes :results output drawer :cache yes :lang elisp
    (dnd-output-ability-constants table)
    #+END_SRC

    #+RESULTS[87ad1d0bfe6e86e226ace44824ec4d05b899ea9a]: define-constants-with-src-block
    :results:
    #+CONSTANTS: STR=9
    #+CONSTANTS: DEX=16
    #+CONSTANTS: CON=19
    #+CONSTANTS: INT=11
    #+CONSTANTS: WIS=11
    #+CONSTANTS: CHA=20
    #+CONSTANTS: PROF=4
    :end:

* Attacks
  #+NAME: attacks
  | Weapon         | Ability | PB | Type     | Die | Mod To Hit | Roll    |
  |----------------+---------+----+----------+-----+------------+---------|
  | Dagger         | DEX     |    | Piercing | 1d8 |          3 | 1d8 + 3 |
  | Light Crossbow | DEX     |    | Piercing | 1d6 |          3 | 1d6 + 3 |
  #+TBLFM: $6='(+ (calc-dnd-pb $PROF $3) (calc-dnd-mod (string-to-number (org-table-get-constant $2))))
  #+TBLFM: $7='(concat $5 " + " (number-to-string (calc-dnd-mod (string-to-number (org-table-get-constant $2)))))

* Feats
** Tough
*** Your hit point maximum increases by an amount equal to twice your level when you gain this feat. Whenever you gain a level thereafter, your hit point maximum increases by an additional 2 hit points
** Metamagic Adept
*** You've learned how to exert your will on your spells to alter how they function:
*** You learn two Metamagic options of your choice from the sorcerer class. You can use only one Metamagic option on a spell when you cast it, unless the option says otherwise. Whenever you reach a level that grants the Ability Score Improvement feature, you can replace one of these Metamagic options with another one from the sorcerer class.
*** You gain 2 sorcery points to spend on Metamagic (these points are added to any sorcery points you have from another source but can be used only on Metamagic). You regain all spent sorcery points when you finish a long rest.
*** Empowered Spell
- When you roll damage for a spell, you can spend 1 sorcery point to reroll a number of the damage dice up to your Charisma modifier (minimum of one). You must use the new rolls.
- You can use Empowered Spell even if you have already used a different Metamagic option during the casting of the spell.
*** Quickened Spell
- When you cast a spell that has a casting time of 1 action, you can spend 2 sorcery points to change the casting time to 1 bonus action for this casting.
*** Twinned Spell
When you cast a spell that targets only one creature and doesn't have a
range of self, you can spend a number of sorcery points equal to the
spell's level to target a second creature in range with the same spell
(1 sorcery point if the spell is a cantrip).

To be eligible, a spell must be incapable of targeting more than one
creature at the spell's current level. For example, [[file:10.spells.org::*Magic Missile][Magic Missile]] and
[[file:10.spells.org::*Scorching Ray][Scorching Ray]] aren't eligible, but [[file:10.spells.org::*Ray of Frost][Ray of Frost]] and /chromatic orb/
are.

Twinned Spell
*** Heightened Spell
When you cast a spell that forces a creature to make a saving throw to
resist its effects, you can spend 3 sorcery points to give one target of
the spell disadvantage on its first saving throw made against the spell.

*** Seeking Spell

* Here be dragons
* base abilities
** str 9
*** -1
** dex 13 +1 (fairy asi) +1 (squat nimbleness) 15
*** +2
** con 9 (19)
*** -1
*** (+4)
** int 11
*** +0
** wis 11
*** +0
** *cha* 14 + 2 (fairy asi) 16
*** +3
*** 4th asi
*** 8th fey touch
*** 12th shadow touch
* datum
** raw
*** 1+2+3+6 = 11 int
*** 2+3+4+4 = 11 str
*** 2+2+3+3 = 8 dump
*** 3+3+5+5 = 13 wis
*** 1+2+2+3 = 7 dump
*** 4+5+5+6 = 16 cha
*** reroll:
*** 1+4+5+5 = 14 dex
*** 2+2+3+4 = 9 con
** hit dice
***  12d6

** hit dice raw
*** base 10 + 6 + 6 + 3 + 4 + 5 + 1 + 2 + 4 + 2 + 3 + 2 + 1
*** sum 49 + con mod (48) (12 w/o amulet) + tough feat (24)
*** total 121 (85 w/o amulet)
*** proficiencies
**** weapons
- darts
- slings
- quarterstaves
- light crowsbows
**** saving throws
***** con
***** cha
**** skills 2
***** insight
***** arcana
**** dice set
**** thieves' tools
***** deception
***** stealth
*** passive perception
* Markdown Reference

#+BEGIN_COMMENT
To markup text in Org, simply surround it with one or more marker characters.
*Bold*, /italic/ and _underline_ are fairly intuitive, and the ability to use
+strikethrough+ is a plus.  You can _/*combine*/_ the basic markup in any
order, however ~code~ and =verbatim= need to be the *_~inner-most~_* markers
if they are present since their contents are interpreted =_literally_=.
#+END_COMMENT
