#+title: D&D 12th level fairy run
#+description: D&D 12th level fairy run

* current
** hp
*** max __
*** current :: __
*** temp :: 0
** ac
***
** init
***
** speed
*** 30
** Money
| Copper | Silver | Electrum | Gold | Platinum | Total (gp) |
|--------+--------+----------+------+----------+------------|
|      0 |      0 |        0 | 7250 |        0 |       7250 |
#+TBLFM: $6=(($1/100) + ($2 /10) + ($3 /2) + $4 + ($5 *10 ))
** Sorc Points
**** 14
** passive per
*** 10

* Spell Slots
1. 1st Level
   1. [ ]
   2. [ ]
   3. [ ]
   4. [ ]
2. 2nd Level
   1. [ ]
   2. [ ]
   3. [ ]
3. 3rd Level
   1. [ ]
   2. [ ]
   3. [ ]
4. 4th Level
   1. [ ]
   2. [ ]
   3. [ ]
5. 5th level
   1. [ ]
   2. [ ]
6. 6th Level
   1. [ ]

* Stats
  | Walking Speed | Flying speed | Climbing Speed | Hit Points | AC | Death Saves | Inspiration |
  |---------------+--------------+----------------+------------+----+-------------+-------------|
  |            30 |           30 |             15 | 12/12      | 17 |             |             |

* Constants
  #+NAME: define-constants-with-src-block
  #+BEGIN_SRC elisp :var table=stats :colnames yes :results output drawer :cache yes :lang elisp
    (dnd-output-ability-constants table)
    #+END_SRC

    #+RESULTS[4524a6d2cf914641cbe2c217a42bcd5e3fbb7140]: define-constants-with-src-block
    :results:
    #+CONSTANTS: STR=9
    #+CONSTANTS: DEX=16
    #+CONSTANTS: CON=19
    #+CONSTANTS: INT=11
    #+CONSTANTS: WIS=11
    #+CONSTANTS: CHA=18
    #+CONSTANTS: PROF=4
    :end:

* Traits
  | Level | Race  | Subrace | Class    | Subclass      | Age | Alignment    | Size        |
  |-------+-------+---------+----------+---------------+-----+--------------+-------------|
  |    12 | Fairy |         | Sorcerer | Abberant Mind |  30 | Chaotic Good | Small (3ft) |

* Equipment
  | Name                 | Quantity | Cost (gp) | Weight (lbs) | Total Weight (lbs) | Total Cost (gp) |
  |----------------------+----------+-----------+--------------+--------------------+-----------------|
  | Light Crossbow       |        1 |        25 |            5 |                  5 |              25 |
  | Crossbow bolts       |       40 |         1 |          1.5 |                60. |              40 |
  | Shortsword           |        1 |        10 |            2 |                  2 |              10 |
  | Dagger               |        4 |         2 |            1 |                  4 |               8 |
  | Arcane Focus, Orb    |        1 |        20 |            3 |                  3 |              20 |
  | Backpack             |        1 |         2 |            5 |                  5 |               2 |
  | Ball Bearings (1000) |        2 |         1 |            2 |                  4 |               2 |
  | Healer's Kit         |        1 |         5 |            3 |                  3 |               5 |
  | Crowbar              |        1 |         2 |            5 |                  5 |               2 |
  | Hammer               |        1 |         1 |            3 |                  3 |               1 |
  | Piton                |       10 |       .05 |          .25 |                2.5 |             0.5 |
  | Torch                |       10 |       .01 |            1 |                 10 |             0.1 |
  | Tinderbox            |        1 |        .5 |            1 |                  1 |             0.5 |
  | Ration               |       10 |        .5 |            2 |                 20 |              5. |
  | Bedroll              |        1 |         1 |            2 |                  2 |               1 |
  | Waterskin            |        1 |        .2 |            5 |                  5 |             0.2 |
  | Hempen Rope (50ft)   |        1 |         1 |           10 |                 10 |               1 |
  | Robes                |        1 |         1 |            4 |                  4 |               1 |
  |----------------------+----------+-----------+--------------+--------------------+-----------------|
  | Carry Capacity       |       90 |           |              |              148.5 |           124.3 |
  #+TBLFM: $5=($2 * $4)
  #+TBLFM: $6=($2 * $3)
  #+TBLFM: @>$5=vsum(@<<$5..@>>$5)
  #+TBLFM: @>$6=vsum(@<<$6..@>>$6)
  #+TBLFM: @>$2=($STR * 10)

* Abilities and Skills
  #+name: stats
  | Ability | Score | Mod | PB | Roll      | Skill           |
  |---------+-------+-----+----+-----------+-----------------|
  | STR     |     9 |  -1 |    | 1d20 + -1 | Saving Throw    |
  |         |       |     |    | 1d20 + -1 | Athletics       |
  |---------+-------+-----+----+-----------+-----------------|
  | DEX     |    16 |   3 |    | 1d20 + 3  | Saving Throw    |
  |         |       |     |    | 1d20 + 3  | Acrobatics      |
  |         |       |     |    | 1d20 + 3  | Sleight of Hand |
  |         |       |     |    | 1d20 + 3  | Stealth         |
  |---------+-------+-----+----+-----------+-----------------|
  | CON     |    19 |   4 |  8 | 1d20 + 4  | Saving Throw    |
  |---------+-------+-----+----+-----------+-----------------|
  | INT     |    11 |   0 |    | 1d20 + 0  | Saving Throw    |
  |         |       |     |    | 1d20 + 0  | Arcana          |
  |         |       |     |    | 1d20 + 0  | History         |
  |         |       |     |    | 1d20 + 0  | Investigation   |
  |         |       |     |    | 1d20 + 0  | Nature          |
  |         |       |     |    | 1d20 + 0  | Religion        |
  |---------+-------+-----+----+-----------+-----------------|
  | WIS     |    11 |   0 |    | 1d20 + 0  | Saving Throw    |
  |         |       |     |    | 1d20 + 0  | Animal Handling |
  |         |       |     |    | 1d20 + 0  | Insight         |
  |         |       |     |    | 1d20 + 0  | Medicine        |
  |         |       |     |    | 1d20 + 0  | Perception      |
  |         |       |     |    | 1d20 + 0  | Survival        |
  |---------+-------+-----+----+-----------+-----------------|
  | CHA     |    20 |   4 |  7 | 1d20 + 4  | Saving Throw    |
  |         |       |     |  7 | 1d20 + 4  | Deception       |
  |         |       |     |  7 | 1d20 + 4  | Intimidation    |
  |         |       |     |  0 | 1d20 + 4  | Performance     |
  |         |       |     |    | 1d20 + 4  | Persuasion      |
  |---------+-------+-----+----+-----------+-----------------|
  | PROF    |     4 |     |    |           |                 |
  #+TBLFM: @2$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @4$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @8$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @9$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @15$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @21$3='(calc-dnd-mod (string-to-number (org-table-get-constant $1)))
  #+TBLFM: @2$5..@3$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @2$1))))))
  #+TBLFM: @4$5..@7$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @4$1))))))
  #+TBLFM: @8$5..@8$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @8$1))))))
  #+TBLFM: @9$5..@14$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @9$1))))))
  #+TBLFM: @15$5..@20$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @15$1))))))
  #+TBLFM: @21$5..@25$5='(concat "1d20 + " (number-to-string (+ (calc-dnd-pb $PROF $4) (calc-dnd-mod (string-to-number (org-table-get-constant @21$1))))))

* Attacks
  #+NAME: attacks
  | Weapon     | Ability | PB | Type     | Die | Mod To Hit | Roll     |
  |------------+---------+----+----------+-----+------------+----------|
  | Longbow    | DEX     |    | Piercing | 1d8 |          3 | 1d8 + 3  |
  | Shortsword | STR     |    | Piercing | 1d6 |         -1 | 1d6 + -1 |
  | Shortsword | DEX     |    | Piercing | 1d6 |          3 | 1d6 + 3  |
  #+TBLFM: $6='(+ (calc-dnd-pb $PROF $3) (calc-dnd-mod (string-to-number (org-table-get-constant $2))))
  #+TBLFM: $7='(concat $5 " + " (number-to-string (calc-dnd-mod (string-to-number (org-table-get-constant $2)))))

* Proficiencies
  | Languages | Tools          | Armor   | Weapons |
  |-----------+----------------+---------+---------|
  | Common    | Thieves' Tools | Light   | Simple  |
  | Grung     | Flute          | Medium  | Martial |
  |           |                | Shields |         |

* Info
** Name
*** Misha Cedarsand Prettybug Driftfluff Petalglimmer Silkdale Thundermeadow Morningwort MangoLassi PurpleFleck Lazuli
** Class
*** Sorcerer
** Level
*** 12
** Race
*** Fairy
** Languages
*** common
*** 1 other
** Background
*** Urban Bounty Hunter
**** skill proficiencies
***** deception
***** stealth
**** tool proficiencies
***** gaming set
***** thieves' tools
**** equipment
***** crowbar
***** robes
***** 20 gp
** Alignment
*** chaotic good
** Age
*** 30
** Height
*** 3
** Size
*** small
** Weight
*** 30
** Eyes
*** green
** Skin
*** yes
** Hair
*** yes
** xp
*** somenum
** Speed
*** 30 + 5 (S.N) 35
** HP
*** 1d6 (or 5) + con mod / sorc level after 1st
*** 96? + 24
* personality
** urban bounty hunter
*** ear to the ground
**** You are in frequent contact with people in the segment of society that your chosen quarries move through. These people might be associated with the criminal underworld, the rough-and-tumble folk of the streets, or members of high society. This connection comes in the form of a contact in any city you visit, a person who provides information about the people and places of the local area.
** traits
*** I would rather make a new friend than a new enemy.
** ideals
*** Redemption. There's a spark of good in everyone. (Good)
** bonds
*** I'm guilty of a terrible crime. I hope I can redeem myself for it.
** flaws
*** If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.
* feats
** Tough
*** Your hit point maximum increases by an amount equal to twice your level when you gain this feat. Whenever you gain a level thereafter, your hit point maximum increases by an additional 2 hit points
** Metamagic Adept
*** You've learned how to exert your will on your spells to alter how they function:
*** You learn two Metamagic options of your choice from the sorcerer class. You can use only one Metamagic option on a spell when you cast it, unless the option says otherwise. Whenever you reach a level that grants the Ability Score Improvement feature, you can replace one of these Metamagic options with another one from the sorcerer class.
*** You gain 2 sorcery points to spend on Metamagic (these points are added to any sorcery points you have from another source but can be used only on Metamagic). You regain all spent sorcery points when you finish a long rest.
*** Empowered Spell
- When you roll damage for a spell, you can spend 1 sorcery point to reroll a number of the damage dice up to your Charisma modifier (minimum of one). You must use the new rolls.
- You can use Empowered Spell even if you have already used a different Metamagic option during the casting of the spell.
*** Quickened Spell
- When you cast a spell that has a casting time of 1 action, you can spend 2 sorcery points to change the casting time to 1 bonus action for this casting.
*** Twinned Spell
*** Seeking Spell
*** Hightened Spell

* Equipment
** Weapons
- crossbow, light, 20 bolts
- simple weapon
- two daggers
- Weapon of Warding
** Items
- component pouch
- bedroll
  - 2lb
- blanket
  - 5lb
- healer's kit
  - 3lb
- 4 ball bearing bags
  - 2lbx4
** Wonderous Items
*** Uncommon 3
**** Immovable Rod :dmg:
**** Luckstone :attuned:dmg:
+1 to ability checks and saving throws
**** Weapon of Warning :attuned:dmg:
*** Rare 1
**** Amulet of Health
- Your Constitution score is 19 while you wear this amulet. It has no effect on you if your Constitution is 19 or higher without it.
*** very rare 0
+
  -
  -
*** attunements 3
**** Amulet of Health
**** Luckstone
**** Weapon of Warning
** Dungeoneer's Pack
- backpack
- crowbar
- hammer
- 10 pitons
- 10 torches
- tinderbox
- 10 rations
- waterskin
- hempen rope, 50 ft

* Spells
** Cantrips 8
**** Druidcraft :druid:phb:
- Casting Time :: 1 action
- Range :: 30 feet
- Components :: V, S
- Duration :: Instantaneous

Whispering to the spirits of nature, you create one of the following effects within range:

- You create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24
  hours. The effect might manifest as a golden orb for clear skies, a cloud for rain, falling snowflakes for snow, and
  so on. This effect persists for 1 round.

- You instantly make a flower blossom, a seed pod open, or a leaf bud bloom.

- You create an instantaneous, harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small
  animal, or the faint odor of skunk. The effect must fit in a 5-foot cube.

- You instantly light or snuff out a candle, a torch, or a small campfire.

**** Mind Sliver :sorcerer:warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V
- Duration :: 1 round

You drive a disorienting spike of psychic energy into the mind of one creature you can see within range. The target must succeed on an Intelligence saving throw or take 1d6 psychic damage and subtract 1d4 from the next saving throw it makes before the end of your next turn.

At Higher Levels. This spell’s damage increases by 1d6 when you reach certain levels: 5th level (2d6), 11th level (3d6), and 17th level (4d6).
**** Chill Touch :sorcerer:warlock:wizard:phb:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: 1 Round

You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the
creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can't regain
hit points until the start of your next turn. Until then, the hand clings to the target.

If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.

This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).
**** Mage Hand :artificer:bard:sorcerer:warlock:wizard:
+ Casting Time :: 1 action
+ Range :: 30 feet
+ Components :: V, S
+ Duration :: 1 minute

 A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.

 You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it.

 The hand can’t attack, activate magical items, or carry more than 10 pounds.

**** Shocking Grasp :sorcerer:wizard:
- Casting Time :: 1 action
- Range :: Touch
- Components :: V, S
- Duration :: Instantaneous

Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against
the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target
takes 1d8 lightning damage, and it can't take reactions until the start of its next turn.

The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).

**** Sword Burst :arificer:sorcerer:warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: Self
- Components :: V
- Duration :: Instantaneous
 Fill in later
**** Light :bard:cleric:sorcerer:wizard:phb:
- Casting Time :: 1 action
- Range :: Touch
- Components :: V, M (a firefly or phosphorescent moss)
- Duration :: 1 hour

You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright
light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely
covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an
action.

If you target an object held or worn by a hostile creature, that creature must succeed on a Dexterity saving throw to
avoid the spell.

**** Fire Bolt :artificer:sorcerer:wizard:phb:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: Instantaneous

You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit,
the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.

This spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).



* Spell Slots
1. 1st Level
   1. [ ]
   2. [ ]
   3. [ ]
   4. [ ]
2. 2nd Level
   1. [ ]
   2. [ ]
   3. [ ]
3. 3rd Level
   1. [ ]
   2. [ ]
   3. [ ]
4. 4th Level
   1. [ ]
   2. [ ]
   3. [ ]
5. 5th level
   1. [ ]
   2. [ ]
6. 6th Level
   1. [ ]

** Spells Known
1. 1st
   1. Arms of Hadar (Slotless)
   2. Dissonant Whispers (Slotless)
   3. Faerie Fire (Slotless 1/day /Slot optional)
   4. Chaos Bolt
   5. Mage Armor
   6. Magic Missle
2. 2nd
   1. Calm Emotions (Slotless)
   2. Detect Thoughts (Slotless)
   3. Enlarge/Reduce (Slotless 1/day /Slot optional)
   4. Blur
   5. Flaming Sphere
   6. Warding Wind
3. 3rd
   1. Hunger of Hadar (Slotless)
   2. Sending (Slotless)
   3. Fireball
4. 4th
   1. Evards Black Tentacles (Slotless)
   2. Summon Abberation (Slotless)
   3. Vitriolic Sphere
5. 5th
   1. Rary's Telepathic Bond (Slotless)
   2. Telekinesis (Slotless)
   3. Cloudkill
   4. Hold Monster
   5. Synaptic Static
6. 6th
   1. Disintegrate
** sorcery points
1. Gift of the Protectors
   + Prerequisite: 9th level, Pact of the Tome feature
   + A new page appears in your Book of Shadows. With your permission, a creature can use its action to write its name on that page, which can contain a number of names equal to your proficiency bonus.
   + When any creature whose name is on the page is reduced to 0 hit points but not killed outright, the creature magically drops to 1 hit point instead. Once this magic is triggered, no creature can benefit from it until you finish a long rest.
   + As an action, you can magically erase a name on the page by touching it.
2. Agonizing Blast
   + Prerequisite: Eldritch Blast cantrip
   + When you cast Eldritch Blast, add your Charisma modifier to the damage it deals on a hit.
3. Armor of Shadows
   + You can cast Mage Armor on yourself at will, without expending a spell slot or material components.
     + mage armor
       + 
4. Repelling Blast
   + Prerequisite: Eldritch Blast cantrip
   + When you hit a creature with Eldritch Blast, you can push the creature up to 10 feet away from you in a straight line.
5. Maddening Hex
   + Prerequisite: 5th level, Hex spell or a warlock feature that curses
   + As a bonus action, you cause a psychic disturbance around the target cursed by your Hex spell or by a warlock feature of yours, such as Hexblade’s Curse and Sign of Ill Omen. When you do so, you deal psychic damage to the cursed target and each creature of your choice within 5 feet of it. The psychic damage equals your Charisma modifier (minimum of 1 damage). To use this invocation, you must be able to see the cursed target, and it must be within 30 feet of you.
6. Sculptor of Flesh
   + Prerequisite: 7th level
   + You can cast Polymorph once using a warlock spell slot. You can't do so again until you finish a long rest.
     + polymorph
7. Visions of Distant Realsm
   + Prerequisite: 15th level
   + You can cast Arcane Eye at will, without expending a spell slot.
     + arcane eye
8. Shroud of Shadow
   + Prerequisite: 15th level
   + You can cast Invisibility at will, without expending a spell slot.
     + invisibilty
* base abilities
** str 9
*** -1
** dex 13 +1 (fairy asi) +1 (squat nimbleness) 15
*** +2
** con 9 (19)
*** -1
*** (+4)
** int 11
*** +0
** wis 11
*** +0
** *cha* 14 + 2 (fairy asi) 16
*** +3
*** 4th asi
*** 8th fey touch
*** 12th shadow touch
* patron
** fathomless
*** tentacle of the deep
- At 1st level, you can magically summon a spectral tentacle that strikes at your foes. As a bonus action, you create a 10-foot-long tentacle at a point you can see within 60 feet of you. The tentacle lasts for 1 minute or until you use this feature to create another tentacle.
- When you create the tentacle, you can make a melee spell attack against one creature within 10 feet of it. On a hit, the target takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn. When you reach 10th level in this class, the damage increases to 2d8.
- As a bonus action on your turn, you can move the tentacle up to 30 feet and repeat the attack .
- You can summon the tentacle a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.
*** gift of the sea
-Also at 1st level, you gain a swimming speed of 40 feet, and you can breathe underwater.
*** oceanic soul
-At 6th level, you are now even more at home in the depths. You gain resistance to cold damage. In addition, when you are fully submerged, any creature that is also fully submerged can understand your speech, and you can understand theirs
*** guardian coil
- At 6th level, your Tentacle of the Deeps can defend you and others, interposing itself between them and harm. When you or a creature you can see takes damage while within 10 feet of the tentacle, you can use your reaction to choose one of those creatures and reduce the damage to that creature by 1d8. When you reach 10th level in this class, the damage reduced by the tentacle increases to 2d8.
*** grasping tentacles
- Starting at 10th level, you learn the spell Evard's Black Tentacles. It counts as a warlock spell for you, but it doesn't count against the number of spells you know. You can also cast it once without using a spell slot, and you regain the ability to do so when you finish a long rest.
- Whenever you cast this spell, your patron's magic bolsters you, granting you a number of temporary hit points equal to your warlock level. Moreover, damage can't break your concentration on this spell.
*** fathomless plunge
- When you reach 14th level, you can magically open temporary conduits to watery destinations. As an action, you can teleport yourself and up to five other willing creatures that you can see within 30 feet of you. Amid a whirl of tentacles, you all vanish and then reappear up to 1 mile away in a body of water you've seen (pond size or larger) or within 30 feet of it, each of you appearing in an unoccupied space within 30 feet of the others.
- Once you use this feature, you can't use it again until you finish a short or long rest.
* saving throws
* skills
** deception
* level bonuses
** ability score improvement
*** : 4,8,12,16,19: 1 ablility +2 or 2 ability +1, cap 20
**** 4th +2 CHA
** feats
*** replace asi, same requirements
**** 8th fey touched
- Your exposure to the Feywild's magic has changed you, granting you the following benefits:
- Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.
- You learn the Misty Step spell and one 1st-level spell of your choice. The 1st-level spell must be from the Divination or Enchantment school of magic. You can cast each of these spells without expending a spell slot. Once you cast either of these spells in this way, you can’t cast that spell in this way again until you finish a long rest. You can also cast these spells using spell slots you have of the appropriate level. The spells’ spellcasting ability is the ability increased by this feat.
**** 12th shadow touched
- Your exposure to the Shadowfell's magic has changed you, granting you the following benefits:
- Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.
- You learn the Invisibility spell and one 1st-level spell of your choice. The 1st-level spell must be from the Illusion or Necromancy school of magic. You can cast each of these spells without expending a spell slot. Once you cast either of these spells in this way, you can't cast that spell in this way again until you finish a long rest. You can also cast these spells using spell slots you have of the appropriate level. The spells' spellcasting ability is the ability increased by this feat.
**** 16th tough
- + 40 hp
**** 19th metamagic adept
- empowered spell
- quickened
** mystic arcanum
*** 11th 
**** 6th level warlock spell
*****      once per long rest
*****      no spell slot usage
*** 13th
****  7th level warlock spell
*****      once per long rest
*****      no spell slot usage
*** 15th
****  8th level warlock spell
*****      once per long rest
*****      no spell slot usage
*** 17th
****  9th level warlock spell
*****      once per long rest
*****      no spell slot usage
** eldritch master 
*** 20th
**** spend 1 minute entreating patron to regen pact magic spell slot
**** long rest
** pact of the tome
- Your patron gives you a grimoire called a Book of Shadows. When you gain this feature, choose three cantrips from any class's spell list (the three needn't be from the same list). While the book is on your person, you can cast those cantrips at will. They don't count against your number of cantrips known. If they don't appear on the warlock spell list, they are nonetheless warlock spells for you.
- If you lose your Book of Shadows, you can perform a 1-hour ceremony to receive a replacement from your patron. This ceremony can be performed during a short or long rest, and it destroys the previous book. The book turns to ash when you die.
* additional info
** Grovel, Cower, and Beg
*** As an action on your turn, you can cower pathetically to distract nearby foes. Until the end of your next turn, your allies gain advantage on attack rolls against enemies within 10 feet of you that can see you. Once you use this trait, you can't use it again until you finish a short or long rest.
** Pack Tactics
*** You have advantage on an attack roll against a creature if at least one of your allies is within 5 feet of the creature and the ally isn't incapacitated.
** Sunlight Sensitivity
*** You have disadvantage on attack rolls and on Wisdom (Perception) checks that rely on sight when you, the target of your attack, or whatever you are trying to perceive is in direct sunlight.
** Magic Theme
*** brine-scented shapes of sharks, jellyfish, octopi, and other sea creatures
* datum
** raw
*** 1+2+3+6 = 11 int
*** 2+3+4+4 = 11 str
*** 2+2+3+3 = 8 dump
*** 3+3+5+5 = 13 wis
*** 1+2+2+3 = 7 dump
*** 4+5+5+6 = 16 cha
*** reroll:
*** 1+4+5+5 = 14 dex
*** 2+2+3+4 = 9 con
** hit dice
***  12d6

** hit dice raw
*** base 10 + 6 + 6 + 3 + 4 + 5 + 1 + 2 + 4 + 2 + 3 + 2 + 1
*** sum 49 + con mod (48) + tough feat (40)
*** total _
*** proficiencies
**** weapons
- darts
- slings
- quarterstaves
- light crowsbows
**** saving throws
***** con
***** cha
**** skills 2
***** insight
***** arcana
**** dice set
**** thieves' tools
***** deception
***** stealth
*** passive perception
** 
* markdown ref

#+BEGIN_COMMENT
To markup text in Org, simply surround it with one or more marker characters.
*Bold*, /italic/ and _underline_ are fairly intuitive, and the ability to use
+strikethrough+ is a plus.  You can _/*combine*/_ the basic markup in any
order, however ~code~ and =verbatim= need to be the *_~inner-most~_* markers
if they are present since their contents are interpreted =_literally_=.
#+END_COMMENT
