#+TILE: Ligma - Features
#+STARTUP: content showstars indent
#+FILETAGS: dnd features ligma

* Racial (Fairy)
- Flight ::
    Because of your wings, you have a flying speed equal to your walking speed. You can't use this flying speed if you're wearing medium or heavy armor.

- Fairy Magic ::
    You know the Druidcraft cantrip. Starting at 3rd level, you can cast the Faerie Fire spell with this trait. Starting at 5th level, you can also cast the Enlarge/Reduce spell with this trait. Once you cast Faerie Fire or Enlarge/Reduce with this trait, you can't cast that spell with it again until you finish a long rest. You can also cast either of those spells using any spell slots you have of the appropriate level. Intelligence, Wisdom, or Charisma is your spellcasting ability for these spells when you cast them with this trait (choose when you select this race).


* Class (Abberant Mind Sorcerer)
- Font of Magic ::
   At 2nd level, you tap into a deep wellspring of magic within yourself. This wellspring is represented by sorcery points, which allow you to create a variety of magical effects.

- Sorcery Points ::
  You have 2 sorcery points, and you gain more as you reach higher levels, as shown in the Sorcery Points column of the Sorcerer table. You can never have more sorcery points than shown on the table for your level. You regain all spent sorcery points when you finish a long rest.
  - Flexible Casting ::
    You can use your sorcery points to gain additional spell slots, or sacrifice spell slots to gain additional sorcery points. You learn other ways to use your sorcery points as you reach higher levels.
  - Creating Spell Slots ::
    You can transform unexpended sorcery points into one spell slot as a bonus action on your turn. The Creating Spell Slots table shows the cost of creating a spell slot of a given level. You can create spell slots no higher in level than 5th. Any spell slot you create with this feature vanishes when you finish a long rest.
  - Converting a Spell Slot to Sorcery Points ::
    As a bonus action on your turn, you can expend one spell slot and gain a number of sorcery points equal to the slot's level.

- Metamagic ::
    At 3rd level, you gain the ability to twist your spells to suit your needs. You gain two of the following Metamagic options of your choice. You gain another one at 10th and 17th level.

    You can use only one Metamagic option on a spell when you cast it, unless otherwise noted.
  - Careful Spell ::
     When you cast a spell that forces other creatures to make a saving throw, you can protect some of those creatures from the spell's full force. To do so, you spend 1 sorcery point and choose a number of those creatures up to your Charisma modifier (minimum of one creature). A chosen creature automatically succeeds on its saving throw against the spell.
  - Distant Spell ::
      When you cast a spell that has a range of 5 feet or greater, you can spend 1 sorcery point to double the range of the spell.
      When you cast a spell that has a range of touch, you can spend 1 sorcery point to make the range of the spell 30 feet.
  - Empowered Spell ::
      When you roll damage for a spell, you can spend 1 sorcery point to reroll a number of the damage dice up to your Charisma modifier (minimum of one). You must use the new rolls.
      You can use Empowered Spell even if you have already used a different Metamagic option during the casting of the spell.
  - Extended Spell ::
      When you cast a spell that has a duration of 1 minute or longer, you can spend 1 sorcery point to double its duration, to a maximum duration of 24 hours.
  - Heightened Spell ::
      When you cast a spell that forces a creature to make a saving throw to resist its effects, you can spend 3 sorcery points to give one target of the spell disadvantage on its first saving throw made against the spell.
  - Quickened Spell ::
      When you cast a spell that has a casting time of 1 action, you can spend 2 sorcery points to change the casting time to 1 bonus action for this casting.
  - Seeking Spell ::
      If you make an attack roll for a spell and miss, you can spend 2 sorcerer points to reroll the d20, and you must use the new roll.
      You can use Seeking Spell even if you have already used a different Metamagic option during the casting of the spell.
  - Subtle Spell ::
      When you cast a spell, you can spend 1 sorcery point to cast it without any somatic or verbal components.
  - Transmuted Spell ::
      When you cast a spell that deals a type of damage from the following list, you can spend 1 sorcery point to change that damage type to one of the other listed types: acid, cold, fire, lightning, poison, thunder.
  - Twinned Spell ::
      When you cast a spell that targets only one creature and doesn't have a range of self, you can spend a number of sorcery points equal to the spell's level to target a second creature in range with the same spell (1 sorcery point if the spell is a cantrip). To be eligible, a spell must be incapable of targeting more than one creature at the spell's current level. For example, Magic Missile and Scorching Ray aren't eligible, but Ray of Frost and Chromatic Orb are.

- Ability Score Improvement ::
    When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can't increase an ability score above 20 using this feature.

- Sorcerous Versatility (Optional) ::
    When you reach a level in this class that grants the Ability Score Improvement feature, you can do one of the following, representing the magic within you flowing in new ways:

  - Replace one of the options you chose for the Metamagic feature with a different Metamagic option available to you.
  - Replace one cantrip you learned from this class' spellcasting feature with another cantrip from the sorcerer spell list.

- Magical Guidance (Optional) ::
    When you reach 5th level, you can tap into your inner wellspring of magic to try and conjure success from failure. When you make an ability check that fails, you can spend 1 sorcery point to reroll the d20, and you must use the new roll, potentially turning the failure into a success.

- Sorcerous Restoration ::
  At 20th level, you regain 4 expended sorcery points whenever you finish a short rest.

| Creating Spell Slots |                    |
|----------------------+--------------------|
| Spell Slot Level     | Sorcery Point Cost |
| 1st                  |                  2 |
| 2nd                  |                  3 |
| 3rd                  |                  5 |
| 4th                  |                  6 |
| 5th                  |                  7 |

** Subclass (Abberant Mind)
- Psionic Spells ::
    Starting at 1st level, you learn additional spells when you reach certain levels in this class, as shown on the Psionic Spells table. Each of these spells counts as a sorcerer spell for you, but it doesn't count against the number of sorcerer spells you know.

    Whenever you gain a sorcerer level, you can replace one spell you gained from this feature with another spell of the same level. The new spell must be a divination or an enchantment spell from the sorcerer, warlock, or wizard spell list.

| Psionic Spells |                                                |
|----------------+------------------------------------------------|
| Sorcerer Level | Spells                                         |
|----------------+------------------------------------------------|
| 1st            | Arms of Hadar, Dissonant Whispers, Mind Sliver |
| 3rd            | Calm Emotions, Detect Thoughts                 |
| 5th            | Hunger of Hadar, Sending                       |
| 7th            | Evard's Black Tentacles, Summon Aberration     |
| 9th            | Rary's Telepathic Bond, Telekinesis            |

- Telepathic Speech ::
    Starting at 1st level, you can form a telepathic connection between your mind and the mind of another. As a bonus action, choose one creature you can see within 30 feet of you. You and the chosen creature can speak telepathically with each other while the two of you are within a number of miles of each other equal to your Charisma modifier (minimum of 1 mile). To understand each other, you each must speak mentally in a language the other knows.

    The telepathic connection lasts for a number of minutes equal to your sorcerer level. It ends early if you are incapacitated or die or if you use this ability to form a connection with a different creature.

- Psionic Sorcery ::
    Beginning at 6th level, when you cast any spell of 1st level or higher from your Psionic Spells feature, you can cast it by expending a spell slot as normal or by spending a number of sorcery points equal to the spell's level. If you cast the spell using sorcery points, it requires no verbal or somatic components, and it requires no material components, unless they are consumed by the spell.

- Psychic Defenses ::
    At 6th level, you gain resistance to psychic damage, and you have advantage on saving throws against being charmed or frightened.

- Revelation in Flesh ::
    Beginning at 14th level, you can unleash the aberrant truth hidden within yourself. As a bonus action, you can spend 1 or more sorcery points to magically transform your body for 10 minutes. For each sorcery point you spend, you can gain one of the following benefits of your choice, the effects of which last until the transformation ends:

    You can see any invisible creature within 60 feet of you, provided it isn't behind total cover. Your eyes also turn black or become writhing sensory tendrils.
    You gain a flying speed equal to your walking speed and can hover. As you fly, your skin glistens with mucus or shines with an otherworldly light.
    You gain a swimming speed equal to twice your walking speed, and you can breathe underwater. Moreover, gills grow from your neck or fan out from behind your ears, your fingers become webbed, or you grow writhing cilia that extend through your clothing.
    Your body, along with any equipment you are wearing or carrying, becomes slimy and pliable. You can move through any space as narrow as 1 inch without squeezing, and you can spend 5 feet of movement to escape from nonmagical restraints or being grappled.

- Warping Implosion ::
    At 18th level, you can unleash your aberrant power as a space-warping anomaly. As an action, you can teleport to an unoccupied space you can see within 120 feet of you. Immediately after you disappear, each creature within 30 feet of the space you left must make a Strength saving throw. On a failed save, a creature takes 3d10 force damage and is pulled straight toward the space you left, ending in an unoccupied space as close to your former space as possible. On a successful save, the creature takes half as much damage and isn't pulled.

    Once you use this feature, you can't do so again until you finish a long rest, unless you spend 5 sorcery points to use it again.


* Feats
- Tough ::
    Your hit point maximum increases by an amount equal to twice your level when you gain this feat. Whenever you gain a level thereafter, your hit point maximum increases by an additional 2 hit points

- Metamagic Adept ::
     You've learned how to exert your will on your spells to alter how they function:
    You learn two Metamagic options of your choice from the sorcerer class. You can use only one Metamagic option on a spell when you cast it, unless the option says otherwise. Whenever you reach a level that grants the Ability Score Improvement feature, you can replace one of these Metamagic options with another one from the sorcerer class.
    You gain 2 sorcery points to spend on Metamagic (these points are added to any sorcery points you have from another source but can be used only on Metamagic). You regain all spent sorcery points when you finish a long rest.
  - Empowered Spell ::
    - When you roll damage for a spell, you can spend 1 sorcery point to reroll a number of the damage dice up to your Charisma modifier (minimum of one). You must use the new rolls.
    - You can use Empowered Spell even if you have already used a different Metamagic option during the casting of the spell.
  - Quickened Spell ::
    - When you cast a spell that has a casting time of 1 action, you can spend 2 sorcery points to change the casting time to 1 bonus action for this casting.
  - Twinned Spell ::
      When you cast a spell that targets only one creature and doesn't have a range of self, you can spend a number of sorcery points equal to the spell's level to target a second creature in range with the same spell (1 sorcery point if the spell is a cantrip).

      To be eligible, a spell must be incapable of targeting more than one creature at the spell's current level. For example, [[file:10.spells.org::*Magic Missile][Magic Missile]] and [[file:10.spells.org::*Scorching Ray][Scorching Ray]] aren't eligible, but [[file:10.spells.org::*Ray of Frost][Ray of Frost]] and /chromatic orb/ are.
  - Heightened Spell ::
      When you cast a spell that forces a creature to make a saving throw to resist its effects, you can spend 3 sorcery points to give one target of the spell disadvantage on its first saving throw made against the spell.
  - Seeking Spell ::
    - If you make an attack roll for a spell and miss, you can spend 2 sorcerer points to reroll the d20, and you must use the new roll.
    - You can use Seeking Spell even if you have already used a different Metamagic option during the casting of the spell.


* Background (Urban Bounty Hunter)
  - Ear to the Ground ::
    You are in frequent contact with people in the segment of society that your chosen quarries move through. These
    people might be associated with the criminal underworld, the rough-and-tumble folk of the streets, or members of
    high society. This connection comes in the form of a contact in any city you visit, a person who provides
    information about the people and places of the local area.
