#+FILETAGS: spell cantrip
* Abjuration :abjur:
** Blade Ward      :bard:cleric:warlock:wizard:
- Casting Time :: 1 action
- Range :: Touch
- Components :: V, S
- Duration :: 1 round

You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.
* Conjuration :conj:
* Divination :div:
* Enchantment :ench:
* Evocation :evoc:
** Booming Blade :artificer:sorcerer:warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: Self (5-foot radius)
- Components :: S,M (a melee weapon worth at least 1 sp)
- Duration :: 1 round

  You brandish the weapon used in the spell’s casting and make a melee attack with it against one creature within 5 feet of you. On a hit, the target suffers the weapon attack’s normal effects and then becomes sheathed in booming energy until the start of your next turn. If the target willingly moves 5 feet or more before then, the target takes 1d8 thunder damage, and the spell ends.

  At Higher Levels. At 5th level, the melee attack deals an extra 1d8 thunder damage to the target on a hit, and the damage the target takes for moving increases to 2d8. Both damage rolls increase by 1d8 at 11th level (2d8 and 3d8) and again at 17th level (3d8 and 4d8).

** Eldritch Blast :warlock:phb:
- Casting Time :: 1 action
- Range :: 120 feet
- Components :: V, S
- Duration :: Instantaneous

  A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage.
  At Higher Levels. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level,
  and four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.

** Frostbite :artificer:druid:sorcerer:warlock:wizard:xge:
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V, S
- Duration :: Instantaneous

  You cause numbing frost to form on one creature that you can see within range. The target must make a Constitution saving throw. On a failed save, the target takes 1d6 cold damage, and it has disadvantage on the next weapon attack roll it makes before the end of its next turn.

  At Higher Levels. The spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).

** Green-Flame Blade :artificer:sorcerer:warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: Self (5-foot radius)
- Components :: S, M(a melee weapon worth at least 1 sp)
- Duration :: Instantaneous

    You brandish the weapon used in the spell’s casting and make a melee attack with it against one creature within 5 feet of you. On a hit, the target suffers the weapon attack’s normal effects, and you can cause green fire to leap from the target to a different creature of your choice that you can see within 5 feet of it. The second creature takes fire damage equal to your spellcasting ability modifier.

    At Higher Levels. At 5th level, the melee attack deals an extra 1d8 fire damage to the target on a hit, and the fire damage to the second creature increases to 1d8 + your spellcasting ability modifier. Both damage rolls increase by 1d8 at 11th level (2d8 and 2d8) and 17th level (3d8 and 3d8).

** Lightning Lure :artificer:sorcerer:warlock:wizard:tce:
- Casting Time :: 1 action
- Range :: Self (15-foot radius)
- Components :: V
- Duration :: Instantaneous

    You create a lash of lightning energy that strikes at one creature of your choice that you can see within 15 feet of you. The target must succeed on a Strength saving throw or be pulled up to 10 feet in a straight line toward you and then take 1d8 lightning damage if it is within 5 feet of you.

    At Higher Levels. This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).

** Thunderclap :artificer:bard:druid:sorcerer:warlock:wizard:xge:
- Casting Time :: 1 action
- Range :: Self (5-foot radius)
- Components :: S
- Duration :: Instantaneous

    You create a burst of thunderous sound, which can be heard 100 feet away. Each creature other than you within 5 feet of you must make a Constitution saving throw. On a failed save, the creature takes 1d6 thunder damage.

    At Higher Levels. The spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).

* Illusion :illus:
* Necromancy :necro:
* Transmutation :trans:
